---

#- name: update apt cache
#  apt: update_cache=yes

- name: install daemon
  apt: name=daemon state=present

- name: copy stream binary
  copy: src=stream dest=/usr/bin owner=root group=root directory_mode=755

- name: copy script
  copy: src=run_stream.sh dest=/usr/bin/run_stream.sh owner=root group=root mode=755

- name: run sysbench
  shell: daemon /usr/bin/run_stream.sh
